# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation
# This workflow will download a prebuilt Java version, install dependencies, build and deploy/publish a new release

name: Deploy and Publish

on:
  push:
    branches: [ '**' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Deploy and Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build Spring boot package
      run: |
        echo -e "\nCommand: gradlew assemble"
        ./gradlew assemble
        echo -e "\nCommand: gradlew check"
        ./gradlew check
        echo -e "\nCommand: gradlew install -x check"
        ./gradlew install -x check

    - name: Before Install
      run:  sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml

    - name: Get the version tag
      id: get_version_tag
      run: echo ::set-output name=SOURCE_TAG::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Publish/Deploy to Maven Central
      if: "!startsWith(github.ref, 'refs/tags/v')"
      env:
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        SIGNING_PASSPHRASE: ${{ secrets.SIGNING_PASSPHRASE }}
      run: scripts/deploy_gha.sh

    - name: Publish/Deploy to Git
      if: "startsWith(github.ref, 'refs/tags/v')"
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GH_TOKEN }}
        automatic_release_tag: ${{ steps.get_version_tag.outputs.SOURCE_TAG }}
        prerelease: true
        draft: true
        files: build/libs/watson-spring-boot-starter-${{ steps.get_version_tag.outputs.SOURCE_TAG }}-jar-with-dependencies.jar

    - name: SKIP - Publish/Deploy to Git and Maven Central
      if: "!startsWith(github.ref, 'refs/tags/v')"
      run: |
        echo -e "\nSkipping a deployment with the script provider because this is not a tagged commit - ${GITHUB_REF}\n"
        echo ${{ steps.get_version_tag.outputs.SOURCE_TAG }}
